name: Tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest

        env:
            DEPLOYER_PRIVATE_KEY: ${{ vars.DEPLOYER_PRIVATE_KEY }}

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 18.16.0

            - name: Install dependencies
              run: yarn install

            # This is required separately from yarn test because it generates the typechain definitions
            - name: Compile
              run: yarn compile

            - name: Run unit tests
              run: yarn test
